# Generated by Django 5.1.15 on 2026-10-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_award_existing_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_blacklisted',
            field=models.BooleanField(default=False),
        ),
    ]
