# Generated by Django 5.1.15 on 2026-10-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_resync_image_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastereport',
            name='cleanup_observation',
            field=models.TextField(blank=True, default=''),
        ),
    ]
